// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwuFKBcQEqQqu9A9mE6KFlIV89n4bwAYE',
    appId: '1:979363811566:web:dd6cc97cca294e3f07a3ff',
    messagingSenderId: '979363811566',
    projectId: 'titan-rizen',
    authDomain: 'titan-rizen.firebaseapp.com',
    storageBucket: 'titan-rizen.firebasestorage.app',
    measurementId: 'G-BR2XMVGGEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY4kU-a5Cp5mZMOEHYDdK4SFEnEisXo3M',
    appId: '1:979363811566:android:140e901c5d439e9a07a3ff',
    messagingSenderId: '979363811566',
    projectId: 'titan-rizen',
    storageBucket: 'titan-rizen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXbsy70wC52SIa0oHoMsNYnxoyPNvUBJc',
    appId: '1:979363811566:ios:dbaf65c919cfc50707a3ff',
    messagingSenderId: '979363811566',
    projectId: 'titan-rizen',
    storageBucket: 'titan-rizen.firebasestorage.app',
    iosClientId:
        '979363811566-677e71jbj1o79qo4ufapcltmgn5ijpsc.apps.googleusercontent.com',
    iosBundleId: 'com.example.rizen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXbsy70wC52SIa0oHoMsNYnxoyPNvUBJc',
    appId: '1:979363811566:ios:dbaf65c919cfc50707a3ff',
    messagingSenderId: '979363811566',
    projectId: 'titan-rizen',
    storageBucket: 'titan-rizen.firebasestorage.app',
    iosClientId:
        '979363811566-677e71jbj1o79qo4ufapcltmgn5ijpsc.apps.googleusercontent.com',
    iosBundleId: 'com.example.rizen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwuFKBcQEqQqu9A9mE6KFlIV89n4bwAYE',
    appId: '1:979363811566:web:d73a296c1ee4b53107a3ff',
    messagingSenderId: '979363811566',
    projectId: 'titan-rizen',
    authDomain: 'titan-rizen.firebaseapp.com',
    storageBucket: 'titan-rizen.firebasestorage.app',
    measurementId: 'G-L8LBHBV1FG',
  );
}
